--screen size 6 flat 4 high

os.loadAPI("buttonAPI.lua")

m = peripheral.wrap("top")

function getClick()
   event,side,x,y = os.pullEvent("monitor_touch")
   button.checkxy(x,y)
end


function Rules1()
   button.clearTable()
   button.label(44,2,"Page1")
   button.label(4,2,"Basic Rules:")
   button.label(2,4," 1 No grieving shall be permitted except on weekends not")
   button.label(2,5,"    adhering this rule will result in a ban")
   button.label(2,6," 2 No swearing or derogatory comments will be allowe")
   button.label(2,7," 3 No disruptive arguments/discussions in global chate")
   button.label(2,8,"    (such as political or religious discussions)")
   button.label(2,9," 4 No exploiting of glitches")
   button.label(2,10," 5 No public accusations of rule-breaking ")
   button.label(2,11,"    (there should be an adimin on Teamspeak)")
   button.label(2,12," 6 If there is a duping bug report it immediatly")
   button.label(2,13," 7 If found duping your progress will be reset")
   button.label(2,14," 8 No advertising or spamming of other servers are allowed")
   button.label(2,15," 9 By joining this server you agree to")
   button.label(2,16,"    SpecterNetworks' Terms and Conditions.")
   button.label(2,17," 10 No public descussion of bans")
   button.setTable("Next", Rules2, "", 46,60,23,25)
   --button.setTable("Main Menu", fillTable, "", 2,16,23,25)
   button.screen()
end

function Rules2()
   button.clearTable()
   button.label(44,2,"Page2")
   button.label(4,2,"Playing rules:")
   button.label(2,4," 1 No using mob spawners unless approved by an admin")
   button.label(2,5," 2 Tourches need to be placed in spawnable/Dark areas")
   button.label(2,6,"               (use F7 to see)")
   button.label(2,7," 3 No killing of other players passive mobs")
   button.label(2,8," 4 Do not build very close to other players without their")
   button.label(2,9,"    permission - buildings that violate this rule may")
   button.label(2,10,"       moved to a new location without warning ")
   button.label(2,11," 5 Admins will not spawn in any lost items after")
   button.label(2,12,"              1 week of playing")
   button.label(2,13," 6 Abandoned and incomplete buildings will be removed/areas")
   button.label(2,14,"           reset after 2 weeks of in activity")
   button.label(2,15," 7 Mining is only allowed in the designated mining dimension")
   button.label(2,16,"                   (accessable at spawn)")
   button.label(2,17," 8 In order to reduce lag, we request that redstone circuits")
   button.label(2,18,"            are not on an infinite loop")
   button.label(2,19," 9 No x-raying/hacking/cheating, any use of xray or")
   button.label(2,20,"   ore detection will result in an immediate 1 month ")
   button.label(2,21,"            ban and rollback of all edits. ")
   button.setTable("First Page", Rules1, "", 24,38,23,25)
   button.setTable("Next", Rules3, "", 46,60,23,25)
   button.setTable("Prev", Rules1, "", 2,16,23,25)
   button.screen()
end

function Rules3()
   button.clearTable()
   button.label(44,2,"Page3")
   button.label(4,2,"PvP Rules:")
   button.label(2,4," 1 No harassment or excessive trollingk")
   button.label(2,5," 2 Camping a players base is considered harassment")
   button.label(2,6," 3 No abuse of server protections eg. hide in spawn.")
   button.label(2,7," 4 No PvP in spawn or any other puplic server areas")
   button.label(2,8," 5 Client modifications may not provide an advantage")
   button.label(2,9,"    in PvP (very broad statement, use common sense)")
   button.label(2,10," 6 No griefing of new players (1 week grace)")
   --button.label(2,11,"blank")
   --button.label(2,12,"blank")
   --button.label(2,13,"blank")
   --button.label(2,14,"blank")
   --button.label(2,15,"blank")
   --button.label(2,16,"blank")
   --button.label(2,17,"blank")
   button.setTable("First Pasge", Rules1, "", 24,38,23,25)
   button.setTable("Next", Rules4, "", 46,60,23,25)
   button.setTable("Prev", Rules2, "", 2,16,23,25)
   button.screen()
end

function Rules4()
   button.clearTable()
   button.label(44,2,"Page4")
   button.label(4,2,"Issues:")
   button.label(2,4," *No TP in nether or from nether to overworld or visa versa")
   button.label(2,5,"blank")
   button.label(2,6,"Banned Items:")
   button.label(2,7," * Quarry")
   button.label(2,8," * Missles")
   button.label(2,9," * Nuclear thingies")
   --button.label(2,10,"blank")
   --button.label(2,11,"blank")
   --button.label(2,12,"blank")
   --button.label(2,13,"blank")
   --button.label(2,14,"blank")
   --button.label(2,15,"blank")
   --button.label(2,16,"blank")
   --button.label(2,17,"blank")
   button.setTable("First page", Rules1, "", 24,38,23,25)
   --button.setTable("Next", Rules3, "", 46,60,23,25)
   button.setTable("Prev", Rules1, "", 2,16,23,25)
   button.screen()
end




Rules1()

while true do
   getClick()
end
